{{- if and .Values.trackingServer.basicAuth.enabled (not .Values.trackingServer.basicAuth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.basicAuthSecretName" . }}
stringData:
  basic_auth.ini: |
    [mlflow]
    default_permission = {{ .Values.trackingServer.basicAuth.createSecret.defaultPermission }}
    database_uri = {{ .Values.trackingServer.basicAuth.createSecret.databaseUri }}
    admin_username = {{ .Values.trackingServer.basicAuth.createSecret.adminUsername }}
    admin_password = {{ .Values.trackingServer.basicAuth.createSecret.adminPassword }}
    authorization_function = {{ .Values.trackingServer.basicAuth.createSecret.authorizationFunction }}
{{- end }}
